Added torch equivalent of InterAtomicL2Distances in torch_layers.py
deepchem/deepchem pull request #2934
Opened 2022-06-07 14:09 UTC by atreyamaj

# Pull Request Template

## Description
Added torch equivalent of InterAtomicL2Distances in torch_layers.py.

How should I reflect the change in the docs?
Fix #(issue)

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2022-06-14 10:49 UTC, arunppsg requested changes

2022-06-21 20:18 UTC, atreyamaj commented on deepchem/models/torch_models/layers.py
> +  >>> from deepchem.models.torch_models.layers import InteratomicL2Distances
I have removed the import statements :+1:

2022-06-21 23:58 UTC, rbharath commented
> Some changes not made by me are being shown due to rebasing, please ignore them.

Rebasing should remove all changes that aren't due to this PR. Can you doublecheck to make sure there isn't an error?

2022-06-23 11:31 UTC, atreyamaj commented
> > Some changes not made by me are being shown due to rebasing, please ignore them.
> 
> Rebasing should remove all changes that aren't due to this PR. Can you doublecheck to make sure there isn't an error?

I have rebased again, but the new changes are still there.

2022-06-28 09:35 UTC, arunppsg commented
LGTM! Merging this in.

2022-06-28 09:36 UTC, merged