yapf on deepchem/trans
deepchem/deepchem pull request #3191
Opened 2023-01-19 10:45 UTC by maithili232

# Pull Request Template

## Description

Fix # 3159 

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-01-24 09:47 UTC, advikavs commented on deepchem/trans/transformers.py
>      Parameters
Lines 1063-67 need to be formatted.

2023-01-25 12:32 UTC, advikavs approved these changes
LGTM

2023-01-27 04:48 UTC, gusty1g approved these changes

2023-01-27 04:51 UTC, gusty1g requested changes
fix errors in mypy

2023-01-28 12:48 UTC, gusty1g commented
This is a duplicate of #3170 and it can safely be closed.

2023-01-28 12:48 UTC, closed without merging