yapf on deepchem/utils part two
deepchem/deepchem pull request #3204
Opened 2023-01-26 11:33 UTC by maithili232

# Pull Request Template

## Description

Fix #3159 

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-01-27 05:03 UTC, gusty1g commented on deepchem/utils/evaluate.py
> +      Model to evaluate. Note that this must be a regression or
Formatting of docstrings should be performed in these lines.

2023-01-27 05:04 UTC, gusty1g requested changes
At some parts, docstring should be formatted. Also, the checklist in the pull request template must be filled up.

2023-01-27 12:55 UTC, advikavs commented on deepchem/utils/fake_data_generator.py
> +    Parameters
135-143 needs to be formatted

2023-01-29 18:23 UTC, gusty1g commented
doctest is failing in Unit Test CI for Electron Sampler.

2023-02-02 09:35 UTC, gusty1g approved these changes

2023-02-02 09:35 UTC, merged