yapf fixes on deepchem/utils part three
deepchem/deepchem pull request #3205
Opened 2023-01-26 12:17 UTC by maithili232

# Pull Request Template

## Description

Fix #3159 

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-01-27 05:07 UTC, gusty1g requested changes
At some parts, docstrings are not well formatted. Also, the checklist in the pull request template must be filled up.

2023-01-27 13:03 UTC, advikavs commented on deepchem/utils/molecule_feature_utils.py
> +      """
check indent

2023-01-27 13:06 UTC, advikavs commented on deepchem/utils/noncovalent_utils.py
> +    """
285-301 needs to be formatted

2023-01-29 17:15 UTC, gusty1g approved these changes

2023-01-29 17:15 UTC, merged