Porting EdgeNetwork Layer to Torch
deepchem/deepchem pull request #3258
Opened 2023-02-24 16:58 UTC by riya-singh28

# Pull Request Template

## Description

Fix #(issue)

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-04-01 08:46 UTC, riya-singh28 commented
@ARY2260 Ready for review

2023-04-02 01:57 UTC, rbharath reviewed
Will leave main review to @ARY2260 for this PR but made a few preliminary comments

2023-04-02 01:57 UTC, rbharath commented on deepchem/models/torch_models/layers.py
> +            :param data: A tensor whose segments are to be summed.
Make sure to use numpy docstyle (https://numpydoc.readthedocs.io/en/latest/format.html)

2023-04-02 01:57 UTC, rbharath commented on deepchem/models/torch_models/layers.py
> +class EdgeNetwork(nn.Module):
Make sure to add this new layer to the docs/ folder

2023-04-02 01:57 UTC, rbharath commented on deepchem/models/tests/test_layers.py
> +    torch_layer.W = torch.from_numpy(np.load('assets/edgenetwork_weights.npy'))
You've added 4 different .npy files but it looks like you're only using 2. Can you remove the unused .npy files?

2023-04-02 01:57 UTC, rbharath commented on deepchem/models/torch_models/layers.py
> +            :param data: A pytorch tensor of the data for segmented summation.
Quick reminder to use numpydocs style https://numpydoc.readthedocs.io/en/latest/format.html

2023-04-04 11:46 UTC, ARY2260 commented on deepchem/models/torch_models/layers.py
> +        def unsorted_segment_sum(data, segment_ids, num_segments):
add these functions in the `deepchem/utils/pytorch_utils.py`  file so that others working on porting the layers don't reimplement the functions

2023-04-04 11:46 UTC, ARY2260 commented on deepchem/models/torch_models/layers.py
> +        def unsorted_segment_sum(data, segment_ids, num_segments):
then import from there

2023-04-04 11:46 UTC, ARY2260 commented on deepchem/models/torch_models/layers.py
> +        def segment_sum(data, segment_ids):
add these functions in the `deepchem/utils/pytorch_utils.py`  file so that others working on porting the layers don't reimplement the functions

2023-04-04 11:50 UTC, ARY2260 commented on deepchem/models/torch_models/layers.py
> +            assert all([i in data.shape for i in segment_ids.shape
instead of assertions here, you can log warnings and also add unit tests for these after adding to utils

2023-04-04 11:54 UTC, ARY2260 commented on deepchem/models/torch_models/layers.py
> +        ind = atom_to_pair[:, 0]
type hint for `ind`

2023-04-04 11:54 UTC, ARY2260 commented on deepchem/models/torch_models/layers.py
> +        result = segment_sum(out_squeeze, ind)
type hint for result

2023-04-04 11:56 UTC, ARY2260 requested changes
I have reviewed the PR and suggested some changes

2023-04-05 23:11 UTC, rbharath reviewed
This is nearly ready for merge I think. A couple of minor comments below and we should be able to get this across the finish line

2023-04-05 23:11 UTC, rbharath commented on deepchem/models/torch_models/layers.py
> +        out: torch.Tensor = torch.unsqueeze(atom_features[atom_to_pair[:, 1]],
Yes, @riya-singh28 can you add comments documenting the shapes?

2023-04-05 23:11 UTC, rbharath commented on deepchem/utils/pytorch_utils.py
> +    data: A tensor whose segments are to be summed.
The formatting here is off. You should have:

```
data: torch.Tensor
  A tensor whose ....
```

with the type annotated. Check https://numpydoc.readthedocs.io/en/latest/format.html for more examples

2023-05-29 16:43 UTC, riya-singh28 commented
Due to lot of changes in the upstream, merge conflicts were creating an issue. Hence, a new PR is created and this one is being deleted.
New PR's link - https://github.com/deepchem/deepchem/pull/3414

2023-05-29 16:43 UTC, closed without merging