Porting EdgeNetwork layer to Torch
deepchem/deepchem pull request #3414
Opened 2023-05-29 16:33 UTC by riya-singh28

## Description

Fix #(issue)

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-05-29 16:52 UTC, ARY2260 approved these changes
LGTM, @rbharath please provide the review check.

2023-05-29 17:09 UTC, ARY2260 requested changes
make the docs locally to verify if the changes are reflected in the docs.

2023-06-03 09:47 UTC, riya-singh28 commented
EdgeNetwork Layer ->
<img width="366" alt="image" src="https://github.com/deepchem/deepchem/assets/98592805/661ede12-838f-4c89-939f-6c775410ebe3">

Pytorch utilities ->

<img width="514" alt="image" src="https://github.com/deepchem/deepchem/assets/98592805/0ee572b4-c110-48da-a2a3-f822cc994b11">

2023-06-03 09:52 UTC, riya-singh28 commented
@ARY2260 @rbharath Ready for review.

2023-06-03 10:13 UTC, ARY2260 approved these changes
LGTM, @rbharath, could you please have a look at this PR.

2023-06-12 16:10 UTC, rbharath commented on deepchem/utils/pytorch_utils.py
> +
Can you add a usage example here?

2023-06-12 16:10 UTC, rbharath commented on deepchem/utils/pytorch_utils.py
> +
Can you add a usage example here?

2023-06-12 16:12 UTC, rbharath commented on deepchem/utils/pytorch_utils.py
> +def unsorted_segment_sum(data, segment_ids, num_segments):
To utils.rst

2023-06-12 16:12 UTC, rbharath reviewed
Let's split this PR up into 3 smaller PRs:

1. Unsorted segment sum + tests + docs
2. Segment sum + tests + docs
3. Edge network layer + tests + docs

2023-06-26 16:27 UTC, closed without merging