Weavegather torch
deepchem/deepchem pull request #3448
Opened 2023-06-28 16:46 UTC by NimishaDey

## Description

This PR is to port Weave Gather to PyTorch.

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [x] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [x] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [x] Run `mypy -p deepchem` and check no errors
  - [x] Run `flake8 <modified file> --count` and check no errors
  - [x] Run `python -m doctest <modified file>` and check no errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-07-04 05:49 UTC, rbharath reviewed
@ARY2260 can you do a round of review on this PR? I will do my pass after

2023-07-12 08:47 UTC, ARY2260 requested changes
LGTM, once the test splitting is completed

2023-07-12 08:47 UTC, ARY2260 commented on deepchem/models/tests/test_weave_gather.py
> +    # Try with compression
write this test in a separate function

2023-07-17 16:14 UTC, rbharath approved these changes
LGTM

2023-07-17 16:14 UTC, merged