Adding weighted_skip parameter to MutilayerPerceptron layer
deepchem/deepchem pull request #3494
Opened 2023-07-26 05:09 UTC by riya-singh28

## Description

By Adding weighted_skip parameter to MutilayerPerceptron layer, it can be used for skip connection as well. Hence, it can be used in place of ResidualBlock for Global and Local Message Passing in MXMNet Model.

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-07-26 09:00 UTC, vsomnath requested changes

2023-07-26 09:05 UTC, riya-singh28 commented on deepchem/models/tests/test_layers.py
> +def test_weighted_skip_MultilayerPerceptron():
Yea sure, I will.

2023-07-26 13:01 UTC, ARY2260 approved these changes
LGTM

2023-07-26 13:36 UTC, vsomnath commented
LGTM

2023-07-26 13:37 UTC, vsomnath approved these changes

2023-07-27 23:45 UTC, rbharath approved these changes
LGTM

2023-07-27 23:45 UTC, merged