SAMloader
deepchem/deepchem pull request #3710
Opened 2023-12-13 15:28 UTC by KitVB

## added SAMLoader

Added featurizer, tests, sample files and the loader

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [x] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [x] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [x] Run `mypy -p deepchem` and check no errors
  - [x] Run `flake8 <modified file> --count` and check no errors
  - [x] Run `python -m doctest <modified file>` and check no errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-12-13 19:51 UTC, shreyasvinaya requested changes
some fixes required

2023-12-13 19:51 UTC, shreyasvinaya commented on deepchem/data/data_loader.py
> +import pysam
add this to a try except block

2023-12-13 19:51 UTC, shreyasvinaya commented on deepchem/feat/bio_seq_featurizer.py
> +class SAMFeaturizer:
add docstrings

2023-12-13 19:51 UTC, shreyasvinaya commented on deepchem/feat/bio_seq_featurizer.py
> +        """
use [Numpy style](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) docstrings

2023-12-13 19:51 UTC, shreyasvinaya commented on deepchem/feat/bio_seq_featurizer.py
> +import pysam
add pysam to the testing environment `env_common.yml`

2023-12-13 19:51 UTC, shreyasvinaya commented on deepchem/data/data_loader.py
> +        Parameters
add new line before the start of parameters, [Numpy style](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) docstrings

2023-12-13 19:51 UTC, shreyasvinaya commented on deepchem/data/data_loader.py
> +        Parameters
add new line before the start of parameters

2023-12-13 19:54 UTC, shreyasvinaya commented on deepchem/data/data_loader.py
> +    """
add usage examples

2024-01-12 17:25 UTC, rbharath commented on deepchem/feat/bio_seq_featurizer.py
> +    get_features(samfile)
Should be removed

2024-01-12 17:25 UTC, rbharath commented on deepchem/feat/bio_seq_featurizer.py
> +    Reference Start, CIGAR and Mapping Quality of the alignment in the SAM file.
Expand the docstring here. What is the type of input, what is the type of output?

2024-01-12 17:29 UTC, rbharath commented on deepchem/data/tests/test_sam_loader.py
> +if __name__ == "__main__":
Let's remove this not needed

2024-01-12 17:30 UTC, rbharath commented on deepchem/data/data_loader.py
> +    This class provides methods to load and featurize data from SAM files.
Add a lot more docs. Explain how the SAM format works and provide examples

2024-01-12 17:32 UTC, rbharath commented on deepchem/feat/bio_seq_featurizer.py
> +    >>> features = featurizer.featurize(inputs)
A featurizer should be RAM to RAM and not touch disk. Let's have the featurizer accept a string buffer or some other in memory object

2024-01-12 17:33 UTC, rbharath reviewed
Let's split this into two files, one for the featurizer and one for the loader

2024-01-22 15:35 UTC, closed without merging